### ISSUE TITLE
Taint with Zygorguides only when using Is: UI?

### ISSUE THREAD

**Issue by otakuishi** [ls-/ls_UI#17]
I cannot seem to use this addon with ZygorGuides. 

The scripts window pops up and says a custom script is going to be ran and I accept but then it says zygor guides is interfering. I turn Is: UI (version 3.06 is what I'm using) off and everything works perfectly but when I turn it back on it ends up doing it again. So it leads me to believe there is some sort of taint when the two are being ran together. 

Zygor Guides has quick icons you can click on to perform said action for quests instead of going to your inventory or typing a special command such as when you whistle around Ironforge for Stolen Rams to be herded back into their pen. 

This is as much info as I can give you because I'm not sure what else you need.

**Comment by ls-** [comment]
Hm... I'll look into it.

**Comment by robodude666** [comment]
@ls- You can get a "free trial" which includes a demo version of the guides that go upto lvl 25. Otherwise, you have to pay. And no, it's not legal. Blizzard's ToS prevent addon authors from charging to get access to the addon; tips/donations are allowed, as long as the addon is available for free and can be used for free (i.e. no subscription required).
