### ISSUE TITLE
Something by Blizz side made bugs appear

### ISSUE THREAD

**Issue by Gotxiko** [ls-/ls_UI#28]
![sin titulo](https://cloud.githubusercontent.com/assets/416493/25812453/a47cedcc-3416-11e7-92bb-76c48249cd46.png)

Some artifacts appeared today, Blizz must have done something, didn't touch anything yesterday or today. Yesterday this wasn't here.

**Comment by ls-** [comment]
Yeah, I'm aware of these artefacts...

I think I know why it happens, but I'm quite busy working on new unit frames atm.

**Comment by ls-** [comment]
K, because you're the one who posted on GH, you'll be my ~~guinea pig~~ tester, sorry :D

Open [/core/widgets.lua#L515](https://github.com/ls-/ls_UI/blob/master/core/widgets.lua#L515);
Replace `x:SetTexture(texture..sections[i], true)` w/
```Lua
if i > 4 then
	x:SetTexture(texture..sections[i], true)
else
	x:SetTexture(texture..sections[i])
end
```
Save file and reload UI.

It fixed the issue for me, might not fix it for you though...

**Comment by Gotxiko** [comment]
Problem fixed :D 
Will update this post if something else broke (though shouldn't).

**Comment by ls-** [comment]
Will keep it open for now then :p

**Comment by ls-** [comment]
K, I got 17 reports that this solution fixes the issue, I'm closing this one then :p
