### ISSUE TITLE
Can you make it compatible with Conro

### ISSUE THREAD

**Issue by hadewych** [ls-/ls_UI#42]

**Comment by ls-** [comment]
Sup!

Unfortunately, I can't. It's ConRo that needs to be adjusted to support this addon and not vice versa. And I don't see him doing it because this addon is niche af :D 

Instead of using LibActionButton and its button cache, for instance, that's how AdiButtonAuras works, ConRo requires a lot of manual labour to add support for an addon that uses LAB or one of its numerous forks because it uses buttons' names and so on.

If I used it, I'd patch ConRo the same way I patched AdiButtonAuras in the past, https://github.com/AdiAddons/AdiButtonAuras/pull/315, but I don't use it >_>
