### ISSUE TITLE
Won't work with Pawn

### ISSUE THREAD

**Issue by lynspottery** [ls-/ls_UI#64]
I have been trying to use the addon Pawn with no success.  For some reason your UI refuses to recognize it.  None of the Pawn options can be opened because LS:UI ignores that addon.

I'm also having more problems with it interacting with the game recently.  It seems to lockup when I enter a raid or dungeon and I have to constantly log out of the game and relog just to get it to unlock.  It even stopped me using keypresses halfway through a raid run a couple of weeks ago that I could not even finish that run.

I am going to have to ditch your ui after having used it for several years now.

**Comment by ls-** [comment]
Sup!

Hmmmm...

![image](https://user-images.githubusercontent.com/2725970/161840005-5f7a6bf9-6177-4b3b-9cfe-376bfcaab304.png)

You meant this? Yeah, the character model frame was overlapping with the `Pawn` button, but you could've just reported it and disabled the `Character Frame` in the `Blizzard` config section for the time being.

![image](https://user-images.githubusercontent.com/2725970/161840454-7b72270e-0f87-44e1-acf2-39940ca7fafd.png)

I never add Blizz UI element reworks without a way to disable them in case something gets broken in between patches or there's conflicts with other addons since multiple addons often affect the same UI elements.

As for other issues, I can't help you with those because I've never ever ran into something like that, neither did other users I interact with on the regular basis, I have people who raid with this UI in heroic/mythic without any issues. I simply can't fix something I can't test or reproduce.

If this UI doesn't satisfy your needs, feel free to use something else. I won't blame you or anything like that, I won't beg you to stay, people move on, that's absolutely normal.

**Comment by ls-** [comment]
Anyway, will release an update that contains this fix in a couple of days. Still need to polish some other stuff first.

**Comment by lynspottery** [comment]
Thank you very much for showing me how to disable that unit frame.  It works now.  I'll keep a look out for your update later.
