### ISSUE TITLE
Add Separate Fading Functionality for Pet Frame

### ISSUE THREAD

**Issue by dembro27** [ls-/ls_UI#76]
Hi! Thanks for continuing to develop this great addon, especially adding a toggle for unit frame widgets which I requested at DF launch. I would like separate fading options for the pet frame because I want to fade my player frame out of combat, but I want the pet frame to be fully opaque all the time. I think it worked that way in an earlier version, or I just didn't notice if it's always been this way (I tinker with my UI a lot).

**Comment by ls-** [comment]
Hi! Yeah, I removed it because I thought it's more convenient to have the main frame control its child frame, so player > pet, target > target of target, etc.

I'll consider it, but not now.. 10.1 goes live tomorrow, and I just want to see what breaks and what doesn't during the first week, and after that I'll be adding other stuff 😅

**Comment by dembro27** [comment]
Sure, I can live with it for now! Thanks.

**Comment by ls-** [comment]
I'll readd it with 100100.02 😑
